<h1>Assignment</h1>

1. Create a 4x4 matrix with values ranging from 0 to 
(The following image is just as an example. It doesn't represent the real image of arrays in the question)
![](image/assignment2.png)

In [1]:
import numpy as np

In [2]:
mtx = np.zeros((4,4))

In [3]:
mtx += np.arange(4)

In [4]:
print(mtx)

[[0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]
 [0. 1. 2. 3.]]


2. Create and array with shape of 4x4 and turn it into two arrays along the second axis.

![](image/assignment.png)

In [13]:
import numpy as np

In [15]:
mtx2 = np.arange(16).reshape((4,4))

In [16]:
mtx2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
mtx2 = np.hsplit(mtx2,[2,6])

In [19]:
mtx2

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]]),
 array([], shape=(4, 0), dtype=int32)]

3. soal tambahan:

misalkan kita memiliki data array seperti berikut ini :

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
       
tuliskan proses filtering untuk mendapatkan hanya elemen data yang berupa bilangan prima ? 

jika dilihat dari data, output yang diinginkan : 2, 3, 7, 11, 13, 17, 19, 23

In [20]:
import numpy as np

In [67]:
import math

In [22]:
mtx3 = np.arange(1,26).reshape(5,5)

In [23]:
mtx3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [87]:
for element in np.nditer(mtx3):
    if(element>1 and element%2!= 0 and element != 21 and element !=25 and element!=9 and element!=15 ):
        print(element)

3
5
7
11
13
17
19
23
